services:
  rti-bridge:
    build:
      context: .
    image: rti-ad-series-bridge:2.0.1
    restart: unless-stopped
    network_mode: host
    environment:
      RTI_CONFIG: /config/config.yaml
    volumes:
      - ./config.yaml:/config/config.yaml:ro
