- alias: RTI Zone → Auto Play Sonos (power on or source→1/2)
  id: rti_zone_autoplay_sonos_power_or_source
  mode: parallel
  max: 16
  trigger:
    - platform: state
      entity_id:
        - switch.rti_ad_8x_amp1_kitchen_power
        - switch.rti_ad_8x_amp1_great_room_power
        - switch.rti_ad_8x_amp1_upper_deck_power
        - switch.rti_ad_8x_amp1_master_bed_power
        - switch.rti_ad_8x_amp1_master_bath_power
        - switch.rti_ad_8x_amp1_mom_s_room_power
        - switch.rti_ad_8x_amp1_office_power
        - switch.rti_ad_8x_amp1_craft_room_power
        - switch.rti_ad_8x_amp2_laundry_power
        - switch.rti_ad_8x_amp2_lower_bar_power
        - switch.rti_ad_8x_amp2_golf_room_power
        - switch.rti_ad_8x_amp2_lower_guest_power
        - switch.rti_ad_8x_amp2_fitness_power
        - switch.rti_ad_8x_amp2_walkout_power
        - switch.rti_ad_8x_amp2_pool_power
        - switch.rti_ad_8x_amp2_patio_power
      from: 'off'
      to: 'on'
    - platform: state
      entity_id:
        - select.rti_ad_8x_amp1_kitchen_source
        - select.rti_ad_8x_amp1_great_room_source
        - select.rti_ad_8x_amp1_upper_deck_source
        - select.rti_ad_8x_amp1_master_bed_source
        - select.rti_ad_8x_amp1_master_bath_source
        - select.rti_ad_8x_amp1_mom_s_room_source
        - select.rti_ad_8x_amp1_office_source
        - select.rti_ad_8x_amp1_craft_room_source
        - select.rti_ad_8x_amp2_laundry_source
        - select.rti_ad_8x_amp2_lower_bar_source
        - select.rti_ad_8x_amp2_golf_room_source
        - select.rti_ad_8x_amp2_lower_guest_source
        - select.rti_ad_8x_amp2_fitness_source
        - select.rti_ad_8x_amp2_walkout_source
        - select.rti_ad_8x_amp2_pool_source
        - select.rti_ad_8x_amp2_patio_source
      to: ['1','2']
  variables:
    source_map:
      switch.rti_ad_8x_amp1_kitchen_power: select.rti_ad_8x_amp1_kitchen_source
      switch.rti_ad_8x_amp1_great_room_power: select.rti_ad_8x_amp1_great_room_source
      switch.rti_ad_8x_amp1_upper_deck_power: select.rti_ad_8x_amp1_upper_deck_source
      switch.rti_ad_8x_amp1_master_bed_power: select.rti_ad_8x_amp1_master_bed_source
      switch.rti_ad_8x_amp1_master_bath_power: select.rti_ad_8x_amp1_master_bath_source
      switch.rti_ad_8x_amp1_mom_s_room_power: select.rti_ad_8x_amp1_mom_s_room_source
      switch.rti_ad_8x_amp1_office_power: select.rti_ad_8x_amp1_office_source
      switch.rti_ad_8x_amp1_craft_room_power: select.rti_ad_8x_amp1_craft_room_source
      switch.rti_ad_8x_amp2_laundry_power: select.rti_ad_8x_amp2_laundry_source
      switch.rti_ad_8x_amp2_lower_bar_power: select.rti_ad_8x_amp2_lower_bar_source
      switch.rti_ad_8x_amp2_golf_room_power: select.rti_ad_8x_amp2_golf_room_source
      switch.rti_ad_8x_amp2_lower_guest_power: select.rti_ad_8x_amp2_lower_guest_source
      switch.rti_ad_8x_amp2_fitness_power: select.rti_ad_8x_amp2_fitness_source
      switch.rti_ad_8x_amp2_walkout_power: select.rti_ad_8x_amp2_walkout_source
      switch.rti_ad_8x_amp2_pool_power: select.rti_ad_8x_amp2_pool_source
      switch.rti_ad_8x_amp2_patio_power: select.rti_ad_8x_amp2_patio_source
    sonos_map:
      '1': media_player.sonos_1
      '2': media_player.sonos_2
  action:
    - variables:
        target_player: >-
          {% if 'power' in trigger.entity_id %}
            {% set source_entity = source_map.get(trigger.entity_id) %}
            {% set source_num = states(source_entity) | int(0) | string %}
          {% else %}
            {% set source_num = trigger.to_state.state | int(0) | string %}
          {% endif %}
          {{ sonos_map.get(source_num) }}
    - condition: template
      value_template: "{{ target_player is not none and states(target_player) != 'playing' }}"
    - service: media_player.media_play
      target: { entity_id: "{{ target_player }}" }
